version: '3'
services:
  spring-boot:
    image: uday07/elastic-search-demo
    container_name: springboot-app-for-elastic-search-demo
    ports:
      - "8081:8081"
    environment:
      - ELASTICSEARCH_CONNECTION_URL=elasticsearch-for-elastic-search-demo:9200
    depends_on:
      - elasticsearch
    networks:
      - elsticsearch-network
    restart: on-failure
  kibana:
    image: docker.elastic.co/kibana/kibana:6.8.12
    container_name: kibana-for-elastic-search-demo
    ports:
      - "5601:5601"
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
    networks:
      - elsticsearch-network
    restart: on-failure
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    container_name: elasticsearch-for-elastic-search-demo
    ports:
      - 9300:9300
      - 9200:9200
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
       soft: -1
       hard: -1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - elsticsearch-network
    restart: on-failure

volumes:
  elasticsearch-data:
    driver: local

networks:
  elsticsearch-network: